# Generated by Django 5.2.6 on 2025-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysuperstudent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mysuperstudent',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='mysuperstudent',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='mysuperstudent',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysuperstudent',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mysuperstudent',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mysuperstudent',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
